Travis build fix
### What is this PR for?
A lot of time travis fails with

    Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.77 sec <<< FAILURE! - in org.apache.zeppelin.notebook.NotebookTest
    testSelectingReplImplementation(org.apache.zeppelin.notebook.NotebookTest)  Time elapsed: 0.025 sec  <<< ERROR!
    org.apache.zeppelin.interpreter.InterpreterException: mock2 interpreter not found
    	at org.apache.zeppelin.notebook.NoteInterpreterLoader.get(NoteInterpreterLoader.java:148)
    	at org.apache.zeppelin.notebook.Note.run(Note.java:365)
    	at org.apache.zeppelin.notebook.NotebookTest.testSelectingReplImplementation(NotebookTest.java:119)

    .
    .
    .
    .

    Tests in error:
      NotebookTest.testSelectingReplImplementation:119 Â» Interpreter mock2 interpret...

This is fix for that error, this doesn't happens always. But here is a lot when this failed last time. https://s3.amazonaws.com/archive.travis-ci.org/jobs/102172625/log.txt

### What type of PR is it?
Improvement

### Todos
* [x] - Clear registered interpreters after a test case is executed.

### Is there a relevant Jira issue?
N/A

Author: Prabhjyot Singh <prabhjyotsingh@gmail.com>

Closes #642 from prabhjyotsingh/travisBuildFix and squashes the following commits:

ddda3c5 [Prabhjyot Singh] registeredInterpreters.clear() in tearDown
b07bca7 [Prabhjyot Singh] instead of 2 create 1 directory