[ZEPPELIN-768] HBase 1.1.x and 1.2.0 release support documentation
### What is this PR for?
When run with HBase 1.1.x or HBase 1.2.0, this error is reported:
```
org.jruby.exceptions.RaiseException: (NameError) cannot load Java class org.apache.hadoop.hbase.quotas.ThrottleType
	at org.jruby.javasupport.JavaUtilities.get_proxy_or_package_under_package(org/jruby/javasupport/JavaUtilities.java:54)
	at (Anonymous).method_missing(/builtin/javasupport/java.rb:51)
	at (Anonymous).(root)(/opt/hbase-1.1.4/lib/ruby/hbase/quotas.rb:23)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1062)
	at (Anonymous).(root)(/opt/hbase-1.1.4/lib/ruby/hbase/quotas.rb:24)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1062)
	at (Anonymous).(root)(/opt/hbase-1.1.4/lib/ruby/hbase/hbase.rb:96)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1062)
	at (Anonymous).(root)(/opt/hbase-1.1.4/lib/ruby/hbase.rb:105)
```
This PR outlines the step to build Zeppelin to resolve this error.

### What type of PR is it?
Documentation

### Todos
* [x] - Test build and run notebook with HBase 1.1.4
* [x] - Test build and run notebook with HBase 1.2.0
* [x] - Document build steps

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-768

### How should this be tested?
Test build and run notebook with HBase 1.1.4
Test build and run notebook with HBase 1.2.0

### Screenshots (if appropriate)
N/A

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? Yes

Author: Felix Cheung <felixcheung_m@hotmail.com>

Closes #800 from felixcheung/hbase1.2 and squashes the following commits:

cd23ef1 [Felix Cheung] fix typo
7545e98 [Felix Cheung] hbase option in doc