[HOTFIX] add [urls] section in shiro.ini
### What is this PR for?
https://github.com/apache/incubator-zeppelin/pull/625 removed `[urls]` from conf/shiro.ini and that cause following exception on start up
```
ERROR [2016-01-14 20:46:38,646] ({main} EnvironmentLoader.java[initEnvironment]:146) - Shiro environment initialization failed
org.apache.shiro.config.ConfigurationException: Unable to instantiate class [anon] for object named '/**'.  Please ensure you've specified the fully qualified class name correctly.
        at org.apache.shiro.config.ReflectionBuilder.createNewInstance(ReflectionBuilder.java:151)
        at org.apache.shiro.config.ReflectionBuilder.buildObjects(ReflectionBuilder.java:119)
        at org.apache.shiro.config.IniSecurityManagerFactory.buildInstances(IniSecurityManagerFactory.java:161)
        at org.apache.shiro.config.IniSecurityManagerFactory.createSecurityManager(IniSecurityManagerFactory.java:124)
        at org.apache.shiro.config.IniSecurityManagerFactory.createSecurityManager(IniSecurityManagerFactory.java:102)
        at org.apache.shiro.config.IniSecurityManagerFactory.createInstance(IniSecurityManagerFactory.java:88)
        at org.apache.shiro.config.IniSecurityManagerFactory.createInstance(IniSecurityManagerFactory.java:46)
        at org.apache.shiro.config.IniFactorySupport.createInstance(IniFactorySupport.java:123)
        at org.apache.shiro.util.AbstractFactory.getInstance(AbstractFactory.java:47)
        at org.apache.shiro.web.env.IniWebEnvironment.createWebSecurityManager(IniWebEnvironment.java:203)
        at org.apache.shiro.web.env.IniWebEnvironment.configure(IniWebEnvironment.java:99)
        at org.apache.shiro.web.env.IniWebEnvironment.init(IniWebEnvironment.java:92)
        at org.apache.shiro.util.LifecycleUtils.init(LifecycleUtils.java:45)
        at org.apache.shiro.util.LifecycleUtils.init(LifecycleUtils.java:40)
        at org.apache.shiro.web.env.EnvironmentLoader.createEnvironment(EnvironmentLoader.java:221)
        at org.apache.shiro.web.env.EnvironmentLoader.initEnvironment(EnvironmentLoader.java:133)
        at org.apache.shiro.web.env.EnvironmentLoaderListener.contextInitialized(EnvironmentLoaderListener.java:58)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
        at org.eclipse.jetty.server.Server.doStart(Server.java:282)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.apache.zeppelin.server.ZeppelinServer.main(ZeppelinServer.java:114)
Caused by: org.apache.shiro.util.UnknownClassException: Unable to load class named [anon] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.
        at org.apache.shiro.util.ClassUtils.forName(ClassUtils.java:148)
        at org.apache.shiro.util.ClassUtils.newInstance(ClassUtils.java:164)
        at org.apache.shiro.config.ReflectionBuilder.createNewInstance(ReflectionBuilder.java:144)
        ... 29 more
```

### What type of PR is it?
Hot Fix

### Todos
* [x] - fix

### Is there a relevant Jira issue?
no

### How should this be tested?
just build and start zeppelin with default configuration

### Screenshots (if appropriate)

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

Author: Lee moon soo <moon@apache.org>

Closes #639 from Leemoonsoo/hotfix_shiro and squashes the following commits:

7a75c48 [Lee moon soo] Hotfix shiro.ini